# Generated by Django 3.2.6 on 2021-10-20 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Required. 150 characters or fewer. digits only.', max_length=150, null=True, verbose_name='title')),
                ('about', models.TextField(blank=True, null=True, verbose_name='about')),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='category_image/', verbose_name='category_image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(blank=True, help_text='Required. 250 characters or fewer. digits only.', max_length=250, null=True, verbose_name='chapter_name')),
                ('parent_id', models.IntegerField(blank=True, default=0, verbose_name='parent_id')),
                ('about', models.TextField(blank=True, null=True, verbose_name='about')),
                ('discussions', models.TextField(blank=True, null=True, verbose_name='discussions')),
                ('bookmarks', models.TextField(blank=True, null=True, verbose_name='bookmarks')),
                ('status', models.IntegerField(blank=True, null=True, verbose_name='status')),
                ('chapter_file', models.FileField(blank=True, null=True, upload_to='chapter_file/', verbose_name='chapter_file')),
                ('chapter_video', models.CharField(blank=True, max_length=250, null=True, verbose_name='chapter_video')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extra_file', models.FileField(blank=True, null=True, upload_to='chapter_file/', verbose_name='extra_file')),
                ('link', models.CharField(blank=True, default='xxx', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(blank=True, help_text='Required. 250 characters or fewer. digits only.', max_length=250, null=True, verbose_name='course_title')),
                ('author', models.CharField(blank=True, max_length=150, null=True, verbose_name='author')),
                ('about', models.TextField(blank=True, null=True, verbose_name='about')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='rating')),
                ('total_hours', models.CharField(blank=True, max_length=6, null=True, verbose_name='total_hours')),
                ('total_days', models.IntegerField(blank=True, null=True, verbose_name='total_days')),
                ('selling_price', models.CharField(blank=True, max_length=6, null=True, verbose_name='selling_price')),
                ('original_price', models.CharField(blank=True, max_length=6, null=True, verbose_name='original_price')),
                ('status', models.IntegerField(blank=True, null=True, verbose_name='status')),
                ('course_level', models.CharField(blank=True, max_length=20, null=True, verbose_name='course_level')),
                ('bestseller', models.IntegerField(blank=True, null=True, verbose_name='bestseller')),
                ('course_file', models.FileField(blank=True, null=True, upload_to='course_file/', verbose_name='course_file')),
                ('course_video', models.CharField(blank=True, max_length=250, null=True, verbose_name='course_video')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('link', models.CharField(blank=True, default='xxx', max_length=2000)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='course_management.category')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('course', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=66, size=6)),
                ('price', models.IntegerField(blank=True)),
                ('about', models.TextField(blank=True, null=True, verbose_name='about')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_score', to='course_management.chapter')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_score', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz_question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=50, null=True, verbose_name='question')),
                ('marks', models.CharField(blank=True, max_length=50, null=True, verbose_name='marks')),
                ('question_status', models.IntegerField(blank=True, null=True, verbose_name='question_status')),
                ('options', models.TextField(default='xxxx', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_name', to='course_management.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz_ques_answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=100, null=True, verbose_name='answer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='question_id', to='course_management.quiz_question')),
            ],
        ),
        migrations.CreateModel(
            name='PackageAlloted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='package_name', to='course_management.package')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='package_alloted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='course_status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name', to='course_management.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_status', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseAlloted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='course_status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_name', to='course_management.course')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='alloted_courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChapterStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='chapter_status')),
                ('completedVideoLenght', models.DecimalField(decimal_places=3, default=0.0, max_digits=6)),
                ('totalVideoLength', models.DecimalField(decimal_places=3, default=0.0, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name', to='course_management.chapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_status', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='course_management.course'),
        ),
    ]
