# Generated by Django 3.2.6 on 2021-10-25 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz_question',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='score',
            name='chapter_score',
        ),
        migrations.AddField(
            model_name='quiz_question',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_quiz', to='course_management.course'),
        ),
        migrations.AddField(
            model_name='score',
            name='course_score',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_score', to='course_management.course'),
        ),
    ]
