# Generated by Django 3.2.6 on 2021-10-27 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0005_auto_20211027_0356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='bestseller',
        ),
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_level',
        ),
        migrations.RemoveField(
            model_name='course',
            name='original_price',
        ),
        migrations.RemoveField(
            model_name='course',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='course',
            name='selling_price',
        ),
        migrations.RemoveField(
            model_name='course',
            name='total_days',
        ),
        migrations.RemoveField(
            model_name='course',
            name='total_hours',
        ),
    ]
