# Generated by Django 3.2.6 on 2021-10-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0006_auto_20211027_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapterstatus',
            name='completedVideoLenght',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='chapterstatus',
            name='totalVideoLength',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
