# Generated by Django 3.2.6 on 2021-11-16 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_management', '0007_auto_20211029_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='certificate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_score', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_completed', to='course_management.course')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_certificate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
