# Generated by Django 3.2.6 on 2021-11-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0009_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='selling_price',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='selling_price'),
        ),
    ]
