# Generated by Django 3.2.6 on 2021-11-23 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0010_course_selling_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='payment_link',
        ),
    ]
