# Generated by Django 3.2.6 on 2021-11-24 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_management', '0011_remove_package_payment_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=250, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=250, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=250, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_payment', to='course_management.course')),
                ('packge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_payment', to='course_management.package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_payment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
