# Generated by Django 3.2.6 on 2021-11-26 11:19

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0013_score_ispass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='course',
            field=django_mysql.models.ListCharField(models.CharField(max_length=200), max_length=6600, size=6),
        ),
    ]
